- name: Install needrestart releated packages
  become: true
  ansible.builtin.apt:
    force_apt_get: false
    name:
      - libpam-systemd
      - needrestart
    state: present
    update_cache: false
