namespace: bartmichu
name: ubuntu_maintenance
version: 2.0.16
description: A collection of Ubuntu maintenance playbooks and roles
tags: ['linux', 'ubuntu', 'maintenance', 'bootstrap', 'account', 'update', 'upgrade', 'apt', 'reboot', 'restart', 'security']

repository: https://github.com/bartmichu/ubuntu_maintenance_collection.git
documentation: https://github.com/bartmichu/ubuntu_maintenance_collection
homepage: https://github.com/bartmichu/ubuntu_maintenance_collection
issues: https://github.com/bartmichu/ubuntu_maintenance_collection/issues
readme: README.md

dependencies: {}
build_ignore: []

license: MIT
authors:
  - Michał Bartkowiak <bartmichu@gmail.com>
