- name: Check all upgrades # noqa: command-instead-of-module
  # TODO: failed_when: _umc_packages_upgrade_check_all_result.rc != 0
  ansible.builtin.shell:
    cmd: >
      set -o pipefail &&
      /usr/bin/apt-get --simulate upgrade --verbose-versions |
      ( /usr/bin/grep ^Inst || [[ $? -eq 1 ]] ) |
      /usr/bin/cut --delimiter ' ' --fields 2
    executable: /bin/bash
  become: false
  changed_when: false
  failed_when: false
  register: _umc_packages_upgrade_check_all_result

- name: Check security upgrades # noqa: command-instead-of-module
  # TODO: apt-get --simulate upgrade --verbose-versions | awk '/^Inst.*security/ {print $2}'
  # TODO: failed_when: _umc_packages_upgrade_check_security_result.rc != 0
  ansible.builtin.shell:
    cmd: >
      set -o pipefail &&
      /usr/bin/apt-get --simulate upgrade --verbose-versions |
      ( /usr/bin/grep ^Inst || [[ $? -eq 1 ]] ) |
      ( /usr/bin/grep --ignore-case security || [[ $? -eq 1 ]]) |
      /usr/bin/cut --delimiter ' ' --fields 2
    executable: /bin/bash
  become: false
  changed_when: false
  failed_when: false
  register: _umc_packages_upgrade_check_security_result

- name: Set host facts
  ansible.builtin.set_fact:
    _umc_global_upgradeable_packages_all: "{{ ((_umc_packages_upgrade_check_all_result.stdout_lines | default('')) | map('trim')) | list }}"
    _umc_global_upgradeable_packages_security: "{{ ((_umc_packages_upgrade_check_security_result.stdout_lines | default('')) | map('trim')) | list }}"
  become: false
