- name: Reboot system
  ansible.builtin.reboot:
    post_reboot_delay: "{{ umc_system_reboot_delay }}"
  become: true
  register: _umc_system_reboot_result

- name: Set host facts # noqa: no-handler
  when: _umc_system_reboot_result.changed
  ansible.builtin.set_fact:
    _umc_global_reboot_successfull: "{{ true if (_umc_system_reboot_result.rebooted == true) else false }}"
  become: false
