- name: Shutdown system
  become: true
  community.general.shutdown:
    delay: "{{ ubuntu_shutdown_delay }}"
    msg: "{{ ubuntu_shutdown_message }}"
  register: ubuntu_shutdown_result

- name: Set host facts # noqa: no-handler
  when: ubuntu_shutdown_result.changed
  become: false
  ansible.builtin.set_fact:
    ubuntu_shutdown_successfull: "{{ True if (ubuntu_shutdown_result.shutdown == true) else False }}"
