- name: Shutdown system
  become: true
  community.general.shutdown:
    delay: "{{ umc_shutdown_delay }}"
    msg: "{{ umc_shutdown_message }}"
  register: umc_shutdown_result

- name: Set host facts # noqa: no-handler
  when: umc_shutdown_result.changed
  become: false
  ansible.builtin.set_fact:
    umc_shutdown_successfull: "{{ True if (umc_shutdown_result.shutdown == true) else False }}"
