- name: Register services which need to be restarted
  # TODO: failed_when: _umc_services_restart_check_result.rc != ???
  ansible.builtin.shell:
    cmd: >
      set -o pipefail &&
      /usr/sbin/needrestart -b -l -r l |
      /usr/bin/awk '/^NEEDRESTART-SVC/{print $2}'
    executable: /bin/bash
  become: true
  changed_when: false
  register: _umc_services_restart_check_result

- name: Set host facts
  ansible.builtin.set_fact:
    _umc_global_services_to_restart: "{{ (_umc_services_restart_check_result.stdout_lines | default('')) | list }}"
  become: false
