- name: Register services which need to be restarted
  become: true
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: >
      set -o pipefail &&
      /usr/sbin/needrestart -b -l -r l |
      /usr/bin/awk '/^NEEDRESTART-SVC/{print $2}'
  changed_when: false
  # TODO: failed_when: umc_needrestart_check.rc != ???
  register: umc_needrestart_check

- name: Set host facts
  become: false
  ansible.builtin.set_fact:
    umc_services_to_restart: "{{ (umc_needrestart_check.stdout_lines | default('')) | list }}"
