- name: Register services which need to be restarted
  become: true
  ansible.builtin.shell:
    cmd: >
      set -o pipefail &&
      /usr/sbin/needrestart -b -l -r l |
      /usr/bin/awk '/^NEEDRESTART-SVC/{print $2}'
    executable: /bin/bash
  # TODO: failed_when: _umc_needrestart_check.rc != ???
  changed_when: false
  register: _umc_needrestart_check

- name: Set host facts
  become: false
  ansible.builtin.set_fact:
    _umc_services_to_restart: "{{ (_umc_needrestart_check.stdout_lines | default('')) | list }}"
