- name: Check for reboot-required flag file
  become: false
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_checksum: false
  register: ubuntu_reboot_sentinel_check

- name: Set host facts
  become: false
  ansible.builtin.set_fact:
    ubuntu_reboot_needed: "{{ True if ubuntu_reboot_sentinel_check.stat.exists else False }}"
    # TODO: implement system_reboot_reason
