- name: Check for reboot-required flag file
  become: false
  ansible.builtin.stat:
    get_checksum: false
    path: /var/run/reboot-required
  register: _umc_reboot_sentinel_check

- name: Set host facts
  become: false
  ansible.builtin.set_fact:
    _umc_reboot_needed: "{{ True if _umc_reboot_sentinel_check.stat.exists else False }}"
    # TODO: implement system_reboot_reason
