- name: Check for reboot-required flag file
  become: false
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_checksum: false
  register: umc_reboot_sentinel_check

- name: Set host facts
  become: false
  ansible.builtin.set_fact:
    umc_reboot_needed: "{{ True if umc_reboot_sentinel_check.stat.exists else False }}"
    # TODO: implement system_reboot_reason
