- name: Check for reboot-required flag file
  ansible.builtin.stat:
    get_checksum: false
    path: /var/run/reboot-required
  become: false
  register: _system_reboot_check_result

- name: Set host facts
  # TODO: implement system_reboot_reason
  ansible.builtin.set_fact:
    _umc_reboot_needed: "{{ True if _system_reboot_check_result.stat.exists else False }}"
  become: false
