- name: Reboot system
  ansible.builtin.reboot:
    post_reboot_delay: "{{ umc_post_reboot_delay }}"
  become: true
  register: _system_reboot_result

- name: Set host facts # noqa: no-handler
  when: _system_reboot_result.changed
  ansible.builtin.set_fact:
    _umc_reboot_successfull: "{{ True if (_system_reboot_result.rebooted == true) else False }}"
  become: false
