- name: Ubuntu Maintenance Collection - Reboot if needed and allowed
  hosts: all
  gather_facts: true

  tasks:

    - name: Gather the package facts
      become: false
      ansible.builtin.package_facts:
        manager: apt

    - name: Installation block
      when: "'needrestart' not in ansible_facts.packages"
      block:

        - name: Run packages_update_cache role
          ansible.builtin.include_role:
            name: packages_update_cache

        - name: Run packages_needrestart role
          ansible.builtin.include_role:
            name: packages_needrestart

    - name: Run system_reboot_check role
      ansible.builtin.include_role:
        name: system_reboot_check

    - name: Run services_restart_check role
      when: umc_services_reboot | default(False)
      ansible.builtin.include_role:
        name: services_restart_check

    - name: Ensure that required facts are defined outside Jinja
      become: false
      ansible.builtin.set_fact:
        umc_reboot_allowed: "{{ umc_reboot_allowed | default(False) }}"

    - name: Display reboot requirement status
      when: (_umc_reboot_needed | default(False))
            or ((umc_services_reboot | default(False)) and ((_umc_services_to_restart | default([])) | length > 0))
      become: false
      ansible.builtin.debug:
        msg: "SYSTEM REBOOT IS NEEDED{{ ' BUT NOT ALLOWED' if umc_reboot_allowed == False }}"

    - name: Reboot block
      when: ((_umc_reboot_needed | default(False)) or ((umc_services_reboot | default(False)) and ((_umc_services_to_restart | default([])) | length > 0)))
              and (umc_reboot_allowed | default(False))
      block:

        - name: Run system_reboot role
          ansible.builtin.include_role:
            name: system_reboot

        - name: Confirm successful system reboot
          become: false
          ansible.builtin.debug:
            msg: "SYSTEM WAS SUCCESSFULLY REBOOTED"
          failed_when: not (_umc_reboot_successfull | default(False))
