- name: Ubuntu Maintenance Collection - Reboot if needed and allowed
  gather_facts: true
  hosts: all

  tasks:
    - name: Ensure that required variables are defined outside Jinja
      ansible.builtin.import_role:
        name: bartmichu.ubuntu_maintenance._umc_validate_globals
      become: false
      tags: always

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: apt
      become: false

    - name: Installation block
      when: "'needrestart' not in ansible_facts.packages"
      block:
        - name: Run umc_packages_update_cache role
          ansible.builtin.include_role:
            name: umc_packages_update_cache

        - name: Run umc_packages_needrestart role
          ansible.builtin.include_role:
            name: umc_packages_needrestart

    - name: Run umc_system_reboot_check role
      ansible.builtin.include_role:
        name: umc_system_reboot_check

    - name: Run umc_services_restart_check role
      when: umc_global_services_require_reboot | default(false)
      ansible.builtin.include_role:
        name: umc_services_restart_check

    - name: Display reboot requirement status
      when: (_umc_global_reboot_needed | default(false))
        or ((umc_global_services_require_reboot | default(false)) and ((_umc_global_services_to_restart | default([])) | length > 0))
      ansible.builtin.debug:
        msg: "SYSTEM REBOOT IS NEEDED{{ ' BUT NOT ALLOWED' if umc_global_allow_reboot == false }}"
      become: false

    - name: Reboot block
      when:
        ((_umc_global_reboot_needed | default(false)) or ((umc_global_services_require_reboot | default(false)) and ((_umc_global_services_to_restart | default([])) | length > 0)))
        and umc_global_allow_reboot
      block:
        - name: Run umc_system_reboot role
          ansible.builtin.include_role:
            name: umc_system_reboot

        - name: Confirm successful system reboot
          ansible.builtin.debug:
            msg: "SYSTEM WAS SUCCESSFULLY REBOOTED"
          become: false
          failed_when: not (_umc_global_reboot_successfull | default(false))
