- name: Ubuntu Maintenance Collection - Reboot unconditionally
  gather_facts: true
  hosts: all

  tasks:
    - name: Run umc_system_reboot role
      ansible.builtin.include_role:
        name: umc_system_reboot

    - name: Confirm successful system reboot
      ansible.builtin.debug:
        msg: "SYSTEM WAS SUCCESSFULLY REBOOTED"
      become: false
      failed_when: not (_umc_global_reboot_successfull | default(false))
