- name: Ubuntu Maintenance Collection - Shutdown unconditionally
  hosts: all
  gather_facts: true

  tasks:

    - name: Run system_shutdown role
      ansible.builtin.include_role:
        name: system_shutdown

    - name: Confirm successful system shutdown
      become: false
      ansible.builtin.debug:
        msg: "SYSTEM WAS SUCCESSFULLY SHUTDOWN"
      failed_when: not (_umc_shutdown_successfull | default(False))
