- name: Ubuntu Maintenance Collection - Shutdown unconditionally
  gather_facts: true
  hosts: all

  tasks:
    - name: Run umc_system_shutdown role
      ansible.builtin.include_role:
        name: umc_system_shutdown

    - name: Confirm successful system shutdown
      ansible.builtin.debug:
        msg: "SYSTEM WAS SUCCESSFULLY SHUTDOWN"
      become: false
      failed_when: not (_umc_global_shutdown_successfull | default(false))
