- name: Ubuntu Maintenance Collection - Install all upgrades
  hosts: all
  gather_facts: true

  tasks:

    - name: Gather the package facts
      become: false
      ansible.builtin.package_facts:
        manager: apt

    - name: Update package repositories cache
      ansible.builtin.include_role:
        name: packages_update_cache

    - name: Install needrestart releated packages
      when: "'needrestart' not in ansible_facts.packages"
      ansible.builtin.include_role:
        name: packages_needrestart

    - name: Check for available package upgrades
      ansible.builtin.include_role:
        name: packages_upgrade_check

    - name: Display available package upgrades
      when: ((_umc_upgradeable_packages_all | default([])) | length > 0) or ((_umc_upgradeable_packages_security | default([])) | length > 0)
      become: false
      ansible.builtin.debug:
        msg:
          "{% if (_umc_upgradeable_packages_security | length > 0) %}PENDING SECURITY UPGRADES: {{ _umc_upgradeable_packages_security | length }} ({{ _umc_upgradeable_packages_security | join(', ') }}). {% endif %}\
          {% if (_umc_upgradeable_packages_all | length > 0) %}PENDING UPGRADES: {{ _umc_upgradeable_packages_all | length }} ({{ _umc_upgradeable_packages_all | join(', ') }}). {% endif %}"

    - name: Upgrade all packages
      when: (_umc_upgradeable_packages_all | length > 0) or ((_umc_upgradeable_packages_security | default([])) | length > 0)
      ansible.builtin.include_role:
        name: packages_upgrade_all

    - name: Check if system reboot is required
      ansible.builtin.include_role:
        name: system_reboot_check

    - name: Check if service restart is required
      ansible.builtin.include_role:
        name: services_restart_check

    - name: Ensure that required facts are defined outside Jinja
      become: false
      ansible.builtin.set_fact:
        umc_reboot_allowed: "{{ umc_reboot_allowed | default(False) }}"
        umc_services_reboot: "{{ umc_services_reboot | default(False) }}"

    - name: Display upgrade and reboot summary
      when: ((_umc_upgradeable_packages_security | default([])) | length > 0)
            or ((_umc_upgradeable_packages_all | default([])) | length > 0)
            or ((_umc_services_to_restart | length) > 0)
            or (_umc_reboot_needed | default(False))
      become: false
      ansible.builtin.debug:
        msg:
          "PACKAGES: {{ _umc_upgrade_summary | default('NONE UPGRADED.') }} \
          {% if (_umc_services_to_restart | length > 0) %}SERVICES TO RESTART: {{ _umc_services_to_restart | length }} ({{ _umc_services_to_restart | join(', ') }}). {% endif %}\
          {% if _umc_reboot_needed %}REBOOT IS NEEDED {{ 'AND ALLOWED' if umc_reboot_allowed else 'BUT NOT ALLOWED' }}. {% endif %}\
          {% if (not _umc_reboot_needed and (umc_services_reboot and (_umc_services_to_restart | length > 0))) %}REBOOT IS NEEDED {{ 'AND ALLOWED' if umc_reboot_allowed else 'BUT NOT ALLOWED' }}.{% endif %}"
