- name: Ubuntu Maintenance Collection - Install all upgrades
  hosts: all
  gather_facts: true

  tasks:

    - name: Gather the package facts
      become: false
      ansible.builtin.package_facts:
        manager: apt

    - name: Update package repositories cache
      ansible.builtin.include_role:
        name: packages_update_cache

    - name: Install needrestart releated packages
      when: "'needrestart' not in ansible_facts.packages"
      ansible.builtin.include_role:
        name: packages_needrestart

    - name: Check for available package upgrades
      ansible.builtin.include_role:
        name: packages_upgrade_check

    - name: Display available package upgrades
      when: ((ubuntu_upgradeable_packages | default([])) | length > 0) or ((ubuntu_upgradeable_packages_security | default([])) | length > 0)
      become: false
      ansible.builtin.debug:
        msg:
          "{% if (ubuntu_upgradeable_packages_security | length > 0) %}PENDING SECURITY UPGRADES: {{ ubuntu_upgradeable_packages_security | length }} ({{ ubuntu_upgradeable_packages_security | join(', ') }}). {% endif %}\
          {% if (ubuntu_upgradeable_packages | length > 0) %}PENDING UPGRADES: {{ ubuntu_upgradeable_packages | length }} ({{ ubuntu_upgradeable_packages | join(', ') }}). {% endif %}"

    - name: Upgrade all packages
      when: (ubuntu_upgradeable_packages | length > 0) or ((ubuntu_upgradeable_packages_security | default([])) | length > 0)
      ansible.builtin.include_role:
        name: packages_upgrade_all

    - name: Check if system reboot is required
      ansible.builtin.include_role:
        name: system_reboot_check

    - name: Check if service restart is required
      ansible.builtin.include_role:
        name: services_restart_check

    - name: Ensure that required facts are defined outside Jinja
      ansible.builtin.set_fact:
        ubuntu_reboot_allowed: "{{ ubuntu_reboot_allowed | default(False) }}"
        ubuntu_services_reboot: "{{ ubuntu_services_reboot | default(False) }}"

    - name: Display upgrade and reboot summary
      when: ((ubuntu_upgradeable_packages_security | default([])) | length > 0)
            or ((ubuntu_upgradeable_packages | default([])) | length > 0)
            or ((ubuntu_services_to_restart | length) > 0)
            or (ubuntu_reboot_needed | default(False))
      become: false
      ansible.builtin.debug:
        msg:
          "PACKAGES: {{ ubuntu_upgrade_summary | default('NONE UPGRADED.') }} \
          {% if (ubuntu_services_to_restart | length > 0) %}SERVICES TO RESTART: {{ ubuntu_services_to_restart | length }} ({{ ubuntu_services_to_restart | join(', ') }}). {% endif %}\
          {% if ubuntu_reboot_needed %}REBOOT IS NEEDED {{ 'AND ALLOWED' if ubuntu_reboot_allowed else 'BUT NOT ALLOWED' }}. {% endif %}\
          {% if (not ubuntu_reboot_needed and (ubuntu_services_reboot and (ubuntu_services_to_restart | length > 0))) %}REBOOT IS NEEDED {{ 'AND ALLOWED' if ubuntu_reboot_allowed else 'BUT NOT ALLOWED' }}.{% endif %}"
