- name: Ubuntu Maintenance Collection - Install all upgrades
  gather_facts: true
  hosts: all

  tasks:
    - name: Ensure that required variables are defined outside Jinja
      ansible.builtin.import_role:
        name: bartmichu.ubuntu_maintenance._umc_validate_globals
      become: false
      tags: always

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: apt
      become: false

    - name: Run umc_packages_update_cache role
      ansible.builtin.include_role:
        name: umc_packages_update_cache

    - name: Run umc_packages_needrestart role
      when: "'needrestart' not in ansible_facts.packages"
      ansible.builtin.include_role:
        name: umc_packages_needrestart

    - name: Run umc_packages_upgrade_check role
      ansible.builtin.include_role:
        name: umc_packages_upgrade_check

    - name: Display available package upgrades
      when: ((_umc_global_upgradeable_packages_all | default([])) | length > 0) or ((_umc_global_upgradeable_packages_security | default([])) | length > 0)
      ansible.builtin.debug:
        msg:
          "{% if (_umc_global_upgradeable_packages_security | length > 0) %}PENDING SECURITY UPGRADES: {{ _umc_global_upgradeable_packages_security | length }} ({{ _umc_global_upgradeable_packages_security | join(', ') }}). {% endif %}\
          {% if (_umc_global_upgradeable_packages_all | length > 0) %}PENDING UPGRADES: {{ _umc_global_upgradeable_packages_all | length }} ({{ _umc_global_upgradeable_packages_all | join(', ') }}). {% endif %}"
      become: false

    - name: Run umc_packages_upgrade_all role
      when: (_umc_global_upgradeable_packages_all | length > 0) or ((_umc_global_upgradeable_packages_security | default([])) | length > 0)
      ansible.builtin.include_role:
        name: umc_packages_upgrade_all

    - name: Run umc_system_reboot_check role
      ansible.builtin.include_role:
        name: umc_system_reboot_check

    - name: Run umc_services_restart_check role
      ansible.builtin.include_role:
        name: umc_services_restart_check

    - name: Display upgrade and reboot summary
      when:
        ((_umc_global_upgradeable_packages_security | default([])) | length > 0)
        or ((_umc_global_upgradeable_packages_all | default([])) | length > 0)
        or ((_umc_global_services_to_restart | length) > 0)
        or (_umc_global_reboot_needed | default(false))
      ansible.builtin.debug:
        msg:
          "PACKAGES: {{ _umc_global_upgrade_summary | default('NONE UPGRADED.') }} \
          {% if (_umc_global_services_to_restart | length > 0) %}SERVICES TO RESTART: {{ _umc_global_services_to_restart | length }} ({{ _umc_global_services_to_restart | join(', ') }}). {% endif %}\
          {% if _umc_global_reboot_needed %}REBOOT IS NEEDED {{ 'AND ALLOWED' if umc_global_allow_reboot else 'BUT NOT ALLOWED' }}. {% endif %}\
          {% if (not _umc_global_reboot_needed and (umc_global_services_require_reboot and (_umc_global_services_to_restart | length > 0))) %}REBOOT IS NEEDED {{ 'AND ALLOWED' if umc_global_allow_reboot else 'BUT NOT ALLOWED' }}.{% endif %}"
      become: false
