- name: Upgrade all installed packages
  ansible.builtin.apt:
    force_apt_get: true
    upgrade: "yes"
  become: true
  register: _umc_packages_upgrade_all_result

- name: Set host facts
  ansible.builtin.set_fact:
    _umc_global_upgrade_summary: "{{ (_umc_packages_upgrade_all_result.stdout_lines | select('search', 'upgraded,') | list)[0] }}"
  become: false
